-- 코드를 입력하세요
# SELECT m.TITLE, m.BOARD_ID, s.REPLY_ID, s.WRITER_ID, s.CONTENTS,DATE_FORMAT(s.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE from USED_GOODS_REPLY s join USED_GOODS_BOARD m ON s.BOARD_ID = m.BOARD_ID where YEAR(s.CREATED_DATE)= 2022 AND MONTH(s.CREATED_DATE) = 10 ORDER BY s.CREATED_DATE, m.TITLE;
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD b JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
WHERE YEAR(b.CREATED_DATE) = 2022 AND MONTH(b.CREATED_DATE) = 10
ORDER BY r.CREATED_DATE, b.TITLE;