-- 코드를 입력하세요
-- 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 상위 3개의 맛을 조회하는 SQL 문을 작성해주세요.
WITH TEST AS(
SELECT SHIPMENT_ID,flavor,total_order FROM FIRST_HALF
UNION
SELECT SHIPMENT_ID,flavor,total_order FROM JULY
) 

-- SELECT FLAVOR FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM TEST GROUP BY TOTAL_ORDER ORDER BY TOTAL_ORDER DESC) A LIMIT 3
-- SELECT * FROM TEST
SELECT TEST.FLAVOR FROM TEST GROUP BY TEST.FLAVOR ORDER BY SUM(TEST.TOTAL_ORDER) DESC LIMIT 3
