-- 코드를 입력하세요
-- USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문을 작성해주세요. 결과는 총거래금액을 기준으로 오름차순 정렬해주세요.
# SELECT USER_ID, NICKNAME, TOTAL_SALES
# FROM USED_GOODS_BOARD B
# JOIN USED_GOODS_USER U
# ON B.WRITER_ID = U.USER_ID
# WHERE B.WRITER_ID IN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL FROM USED_GOODS_BOARD GROUP BY WRITER_ID)

WITH TOA AS(
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL FROM USED_GOODS_BOARD WHERE STATUS = "DONE" GROUP BY WRITER_ID
)
SELECT B.USER_ID, B.NICKNAME, A.TOTAL as TOTAL_SALES
FROM TOA A
JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE A.TOTAL >= 700000
ORDER BY A.TOTAL
