-- 코드를 작성해주세요
WITH CTE AS(
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR , MAX(SIZE_OF_COLONY) as MAX_SIZE FROM ECOLI_DATA GROUP BY YEAR
)

SELECT YEAR, B.MAX_SIZE - A.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA A
JOIN CTE B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV
