-- 코드를 입력하세요
WITH RENTAL AS(
    SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-10-01'
)

SELECT DISTINCT A.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR A
JOIN RENTAL B
USING(CAR_ID)
WHERE A.CAR_TYPE LIKE '세단'
ORDER BY A.CAR_ID DESC
