-- 코드를 작성해주세요
WITH DEPT_AVG AS(
SELECT DEPT_ID, ROUND(AVG(SAL),0) AS AVG_SAL
FROM HR_EMPLOYEES
GROUP BY DEPT_ID
)

SELECT A.DEPT_ID, B.DEPT_NAME_EN, A.AVG_SAL
FROM DEPT_AVG A
JOIN HR_DEPARTMENT B
USING(DEPT_ID)
ORDER BY AVG_SAL DESC
